name: Deploy JSON POC

on:
  workflow_dispatch:
    inputs:
      appKey:
        description: App Key
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Repository Structure
        run: |
          ls -R

      - name: Show Application JSON
        run: |
          cat deployment/application.json

      - name: Show Resource JSON
        run: |
          cat deployment/resource.json
